const merchant='merchant_demo';let filter='';
const $=x=>document.getElementById(x);
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=n=>new Intl.NumberFormat('en-IN').format(Number(n||0));
const pc=n=>`${Math.round(Number(n||0)*1000)/10}%`;
const badge=s=>s==='RECONCILED'?'<span class="badge good">RECONCILED</span>':s==='REVIEW'?'<span class="badge warn">REVIEW</span>':'<span class="badge bad">UNRESOLVED</span>';
async function get(path){const r=await fetch(path);if(!r.ok)throw Error(`${r.status}`);return r.json()}
async function overview(){const d=await get(`/api/v1/overview/${merchant}`);const m=Object.fromEntries((d.case_status||[]).map(x=>[x.status,x.c]));const total=(m.RECONCILED||0)+(m.REVIEW||0)+(m.UNRESOLVED||0);const h=total?(m.RECONCILED||0)/total:0;$('health').textContent=pc(h);$('healthNote').textContent=(m.UNRESOLVED||0)?`${m.UNRESOLVED} unresolved cases are blocked.`:'No unresolved cases.';$('records').textContent=fmt(Object.values(d.counts||{}).reduce((a,b)=>a+b,0));$('reconciled').textContent=fmt(m.RECONCILED||0);$('reconciledRate').textContent=`${pc(h)} of reconciliation cases`;$('exceptions').textContent=fmt((m.REVIEW||0)+(m.UNRESOLVED||0));const src=d.records_by_source||[];const mx=Math.max(...src.map(x=>x.c),1);$('sources').innerHTML=src.map(x=>`<div class="src"><label>${esc(x.source)}</label><div class="bar"><i style="width:${Math.round(x.c/mx*100)}%"></i></div><div class="num">${fmt(x.c)}</div></div>`).join('');const a=await get(`/api/v1/dashboard/${merchant}`).catch(()=>({recent_activity:[]}));$('activity').innerHTML=(a.recent_activity||[]).map(x=>`<div class="act"><time>${esc(new Date(x.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))}</time><div><b>${esc(x.event_type)}</b><div class="muted">${esc(x.actor)}</div></div></div>`).join('')||'<div class="act"><div></div><div class="muted">No activity yet.</div></div>'}
async function cases(){const d=await get(`/api/v1/cases/${merchant}${filter?`?status=${filter}`:''}`);const rows=d.items||[];$('caseCount').textContent=fmt(rows.length);$('cases').innerHTML=rows.map(c=>`<div class="row" data-id="${esc(c.case_id)}"><div class="id">${esc(c.case_id)}</div><div class="mainline"><b>${esc(c.primary_record_id)}</b><small>${esc(c.reason||'')}</small></div><div>${badge(c.status)}</div><div class="confidence">${pc(c.confidence)}</div><div>›</div></div>`).join('');document.querySelectorAll('#cases .row').forEach(x=>x.onclick=()=>openCase(x.dataset.id))}
async function exceptions(){const d=await get(`/api/v1/exceptions/${merchant}`);const rows=d.items||[];$('excCount').textContent=fmt(rows.length);$('excList').innerHTML=rows.map(e=>`<div class="row" data-id="${esc(e.case_id)}"><div class="id">${esc(e.exception_id)}</div><div class="mainline"><b>${esc(e.primary_record_id||e.case_id)}</b><small>${esc(e.reason)}</small></div><div><span class="badge ${e.severity==='HIGH'?'bad':'warn'}">${esc(e.severity)}</span></div><div class="confidence">${pc(e.confidence)}</div><div>›</div></div>`).join('');document.querySelectorAll('#excList .row').forEach(x=>x.onclick=()=>openCase(x.dataset.id))}
async function audit(){const d=await get(`/api/v1/dashboard/${merchant}`);$('auditList').innerHTML=(d.recent_activity||[]).map(x=>`<div class="auditrow"><div>${esc(new Date(x.created_at).toLocaleString())}</div><div><b>${esc(x.event_type)}</b></div><div>${esc(x.actor)}</div><pre class="json">${esc(x.payload_json)}</pre></div>`).join('')}
async function resolveCase(id,action){const payment=action==='approve_match'?($('reviewPayment')?.value||''):null;const note=$('reviewNote')?.value||'';if(action==='approve_match'&&!payment){alert('Enter a payment ID first.');return}const r=await fetch(`/api/v1/cases/${encodeURIComponent(id)}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payment_id:payment,note,actor:'dashboard_reviewer'})});if(!r.ok){const e=await r.json().catch(()=>({}));alert(e.detail||'Resolution failed');return}await openCase(id);overview();cases();exceptions();audit()}
async function openCase(id){const d=await get(`/api/v1/cases/detail/${encodeURIComponent(id)}`);const c=d.case;$('dtitle').textContent=c.case_id;const review=(c.status==='REVIEW'||c.status==='UNRESOLVED');const candidateHtml=review?`<div class="reviewbox"><div class="eyebrow">HUMAN REVIEW</div><p class="muted">Confirm a payment only after checking the evidence. This action is permanently audited.</p><div class="candidate-list">${(d.review_candidates||[]).map(x=>`<button class="candidate" onclick="document.getElementById('reviewPayment').value='${esc(x.source_record_id)}'"><b>${esc(x.source_record_id)}</b><span>₹${fmt(x.amount)} · ${esc(x.event_date)} · ${esc(x.customer_name||'')}</span></button>`).join('')||'<span class="muted">No obvious candidates; enter a payment ID manually.</span>'}</div><input id="reviewPayment" class="reviewinput" placeholder="Payment ID, e.g. pay_000123"><input id="reviewNote" class="reviewinput" placeholder="Reviewer note"><div class="reviewactions"><button onclick="resolveCase(''+esc(c.case_id)+'','approve_match')">Approve match</button><button class="reject" onclick="resolveCase(''+esc(c.case_id)+'','reject')">Reject</button></div></div>`:'';$('detail').innerHTML=`<div class="detailgrid"><div class="dc"><label>STATUS</label><b>${badge(c.status)}</b></div><div class="dc"><label>CONFIDENCE</label><b>${pc(c.confidence)}</b></div><div class="dc"><label>PRIMARY</label><b>${esc(c.primary_record_id||'—')}</b></div><div class="dc"><label>MATCHED</label><b>${esc(c.matched_record_id||'—')}</b></div></div><div class="dc"><label>DECISION REASON</label><b>${esc(c.reason||'—')}</b></div>${candidateHtml}<div class="timeline">${(d.links||[]).map(l=>`<div class="ti"><b>Evidence link</b><p>${esc(l.from_source)}:${esc(l.from_source_record_id)} → ${esc(l.to_source)}:${esc(l.to_source_record_id)}<br>confidence ${pc(l.confidence)}</p></div>`).join('')}${(d.exceptions||[]).map(e=>`<div class="ti"><b>Exception</b><p>${esc(e.severity)} · ${esc(e.reason)}<br>Status: ${esc(e.status)}</p></div>`).join('')}</div>`;$('drawer').classList.remove('hidden')}
function view(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('title').textContent={overview:'Finance overview',reconciliation:'Reconciliation cases',exceptions:'Exception queue',audit:'Audit trail'}[v];if(v==='overview')overview();if(v==='reconciliation')cases();if(v==='exceptions')exceptions();if(v==='audit')audit()}
document.querySelectorAll('nav button').forEach(x=>x.onclick=()=>view(x.dataset.view));document.querySelectorAll('.f').forEach(x=>x.onclick=()=>{document.querySelectorAll('.f').forEach(y=>y.classList.remove('active'));x.classList.add('active');filter=x.dataset.status;cases()});$('refresh').onclick=()=>view(document.querySelector('nav button.active').dataset.view);$('close').onclick=()=>$('drawer').classList.add('hidden');$('shade').onclick=()=>$('drawer').classList.add('hidden');overview();
